(function(){
  'use strict';
  const M=window.GroupingModel;
  let modal,data,state,nodes=[],raf=0,lastFrame=0,drag=null;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const student=id=>data.students.find(s=>String(s.id)===String(id));
  const zoneFor=id=>id==='unassigned'?null:state.groups.find(g=>g.id===id);
  const setMessage=(value,kind='')=>{const el=modal?.querySelector('.group-message');if(el){el.textContent=value||'';el.className=`group-message ${kind}`}};
  const bubbleHtml=id=>{const s=student(id),leader=state.groups.some(g=>g.leaderId===String(id));return s?`<button class="group-bubble ${leader?'is-leader':''}" data-student="${esc(id)}" aria-label="${esc(s.name)} ${esc(s.studentNo)}${leader?'，组长':''}"><span class="group-no">${leader?'★ ':''}${esc(String(s.studentNo||'').slice(-2))}</span><span class="group-name">${esc(Array.from(s.name||'?').slice(-1).join(''))}</span></button>`:''};
  function zoneHtml(id,title,max){const ids=id==='unassigned'?state.unassignedIds:state.groups.find(g=>g.id===id)?.studentIds||[];const count=id==='unassigned'?'公共池':`${ids.length}/${max}`;return `<section class="group-zone ${id==='unassigned'?'public-zone':''}" data-zone="${esc(id)}"><header><b>${esc(title)}</b><span>${count}</span>${id!=='unassigned'?`<label>上限 <input data-max="${esc(id)}" type="number" min="1" max="100" value="${max}" ${state.locked?'disabled':''}></label>`:''}</header><div class="zone-canvas"><div class="zone-hint">${id==='unassigned'?'拖入任意小组':'拖入学生；长按设置组长'}</div>${ids.map(bubbleHtml).join('')}</div></section>`}
  function render(){
    if(!modal)return;
    modal.querySelector('.group-count').value=state.groups.length;
    modal.querySelector('.group-lock').textContent=state.locked?'🔒 分组已锁定':'🔓 已解锁，可拖动设置';
    modal.querySelector('.group-lock').classList.toggle('unlocked',!state.locked);
    modal.querySelector('[data-resize]').disabled=state.locked;
    modal.querySelector('.group-layout').innerHTML=zoneHtml('unassigned','公共池')+state.groups.map(g=>zoneHtml(g.id,g.name,g.max)).join('');
    modal.querySelector('.committee').innerHTML='<h3>班委设置</h3>'+M.ROLES.map(r=>`<label>${r}<select data-role="${r}" ${state.locked?'disabled':''}><option value="">未设置</option>${data.students.map(s=>`<option value="${esc(s.id)}" ${state.committee[r]===String(s.id)?'selected':''}>${esc(s.studentNo)} ${esc(s.name)}</option>`).join('')}</select></label>`).join('');
    requestAnimationFrame(()=>{createPhysicsNodes();startPhysics()});
  }
  function createPhysicsNodes(){nodes=[];modal.querySelectorAll('.group-zone').forEach(zone=>{const canvas=zone.querySelector('.zone-canvas');zone.querySelectorAll('[data-student]').forEach((el,i)=>{const id=el.dataset.student,n={id,zone:zone.dataset.zone,el,x:8+(i%5)*78,y:10+Math.floor(i/5)*78,vx:0,vy:0,r:38,hover:false,sleeping:false};el.style.transform=`translate3d(${n.x}px,${n.y}px,0)`;nodes.push(n);bindBubble(n,canvas)});});}
  const zoneNodeList=zone=>nodes.filter(n=>n.zone===zone);
  function setPreview(target){modal.querySelectorAll('.group-zone').forEach(z=>{const blocked=target&&target!=='unassigned'&&((state.groups.find(g=>g.id===target)?.studentIds.length||0)>=(state.groups.find(g=>g.id===target)?.max||0));z.classList.toggle('target-preview',!!target&&z.dataset.zone===target);z.classList.toggle('drop-blocked',!!blocked&&z.dataset.zone===target);});}
  function bindBubble(n,canvas){
    const el=n.el;
    el.addEventListener('pointerdown',e=>{if(state.locked||e.button!==0)return;e.preventDefault();const rect=canvas.getBoundingClientRect();drag={id:n.id,source:n.zone,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,moved:false,longPressed:false,pressTimer:setTimeout(()=>{if(!drag||drag.moved||drag.id!==n.id)return;drag.longPressed=true;const g=zoneFor(n.zone);if(g){if(g.leaderId===n.id)g.leaderId=null;else M.leader(state,n.zone,n.id);setMessage(g.leaderId===n.id?`已将 ${student(n.id)?.name||''} 设为${g.name}组长`:`已取消 ${student(n.id)?.name||''} 的组长身份`,'ok');render()}},620)};n.hover=true;n.sleeping=false;n.grabX=e.clientX-rect.left-n.x;n.grabY=e.clientY-rect.top-n.y;el.setPointerCapture?.(e.pointerId);el.classList.add('dragging');});
    el.addEventListener('pointermove',e=>{if(!drag||drag.pointerId!==e.pointerId||drag.id!==n.id)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>7){drag.moved=true;clearTimeout(drag.pressTimer);const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group-zone');setPreview(zone?.dataset.zone||null);const rect=canvas.getBoundingClientRect();n.x=Math.max(2,Math.min(canvas.clientWidth-78,e.clientX-rect.left-n.grabX));n.y=Math.max(2,Math.min(canvas.clientHeight-78,e.clientY-rect.top-n.grabY));n.vx=n.vy=0;el.style.transform=`translate3d(${n.x}px,${n.y}px,0)`;}});
    const finish=e=>{if(!drag||drag.pointerId!==e.pointerId||drag.id!==n.id)return;clearTimeout(drag.pressTimer);const d=drag;drag=null;el.classList.remove('dragging');setPreview(null);n.hover=false;if(!d.moved||d.longPressed)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group-zone')?.dataset.zone;if(!target||target===d.source){startPhysics();return}try{if(target==='unassigned')M.remove(state,d.id);else M.add(state,d.id,target);setMessage(`已移动 ${student(d.id)?.name||''}；保存后同步云端`,'ok');render()}catch(error){setMessage(error.message,'error');render()}};
    el.addEventListener('pointerup',finish);el.addEventListener('pointercancel',finish);el.addEventListener('lostpointercapture',finish);
  }
  function startPhysics(){cancelAnimationFrame(raf);lastFrame=performance.now();const tick=now=>{if(!modal.classList.contains('open'))return;const dt=Math.min(.025,(now-lastFrame)/1000);lastFrame=now;nodes.forEach(n=>{const canvas=n.el.closest('.zone-canvas');if(canvas)window.BubblePhysics?.step(zoneNodeList(n.zone),dt,{width:canvas.clientWidth,ground:Math.max(2,canvas.clientHeight-78),gravityY:95})});nodes.forEach(n=>{n.el.style.transform=`translate3d(${n.x}px,${n.y}px,0)`});raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)}
  async function save(){const button=modal.querySelector('[data-save]');button.disabled=true;try{const old=JSON.parse(JSON.stringify(data)),next=JSON.parse(JSON.stringify(data));next.grouping=state;await window.saveScheduleCloud(next,old);window.classroomCloudBridge.setData(next);data=next;setMessage('保存成功，云端已同步','ok')}catch(e){setMessage(`保存失败：${e.message}（原数据未覆盖）`,'error')}finally{button.disabled=false}}
  function open(){data=JSON.parse(JSON.stringify(window.classroomCloudBridge.getData()));state=M.normalize(data.grouping,data.students);state.locked=state.locked!==false;modal.classList.add('open');render();setMessage(state.locked?'分组默认锁定，请先解锁后修改':'已解锁，可拖动分组')}
  function resizeGroups(){if(state.locked)return;const n=Math.max(1,Math.min(30,Number(modal.querySelector('.group-count').value)||1));while(state.groups.length<n){const i=state.groups.length+1;state.groups.push({id:'group-'+i,name:'第'+i+'组',max:4,studentIds:[],leaderId:null})}while(state.groups.length>n){const g=state.groups.pop();state.unassignedIds.push(...g.studentIds);if(g.leaderId)g.leaderId=null}state.groupCount=n;render()}
  function init(){
    const entry=document.createElement('button');entry.className='btn';entry.id='groupingEntry';entry.textContent='分组与班委';document.querySelector('#rosterManageBtn')?.after(entry);entry.onclick=open;
    modal=document.createElement('div');modal.id='groupingModal';modal.innerHTML='<section class="grouping-panel"><button class="grouping-close" aria-label="关闭">×</button><h2>分组与班委</h2><p class="group-note">公共池与每个小组都使用首页同一套气泡碰撞物理。分组页不显示班委特权；长按组内气泡设置或取消组长。</p><div class="group-toolbar"><label>分组数 <input class="group-count" type="number" min="1" max="30"></label><button data-resize>调整组数</button><button class="group-lock" type="button">🔒 分组已锁定</button><button data-save>保存到云端</button></div><p class="group-message"></p><div class="group-layout"></div><aside class="committee"></aside></section>';document.body.append(modal);
    modal.querySelector('.grouping-close').onclick=()=>{modal.classList.remove('open');cancelAnimationFrame(raf)};modal.querySelector('[data-save]').onclick=save;modal.querySelector('[data-resize]').onclick=resizeGroups;modal.querySelector('.group-lock').onclick=()=>{state.locked=!state.locked;render();setMessage(state.locked?'分组已锁定':'已解锁，可拖动、长按和修改','ok')};
    modal.addEventListener('change',e=>{try{if(e.target.dataset.max&&!state.locked)M.max(state,e.target.dataset.max,e.target.value);if(e.target.dataset.role&&!state.locked)M.role(state,e.target.dataset.role,e.target.value);render()}catch(x){setMessage(x.message,'error');render()}});
  }
  document.addEventListener('DOMContentLoaded',init);
})();
