(function(){
  const M=window.GroupingModel; let modal, current, state, dragId=null, longPress=null, suppressClick=false;
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function toast(msg){const el=document.querySelector('#toast');if(el){el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}}
  function student(id){return current.students.find(s=>String(s.id)===String(id))||{id,name:'?',studentNo:'??',emoji:'🙂'}}
  function label(s){return `${esc(String(s.studentNo||'').slice(-2))} ${esc(String(s.name||'').slice(-1)||'?')}`}
  function open(){current=window.classroomCloudBridge&&window.classroomCloudBridge.getData();if(!current||!Array.isArray(current.students)){toast('请先加载班级名单');return}state=M.normalize(current.grouping,current.students);render();modal.classList.add('open')}
  function close(){modal.classList.remove('open');dragId=null}
  function save(){current.grouping=state; if(window.classroomCloudBridge&&window.classroomCloudBridge.setData)window.classroomCloudBridge.setData(current); if(window.cloudDataChanged)window.cloudDataChanged(current); toast('分组与班委已保存到云端');}
  function bubble(id,extra){const s=student(id), committee=Object.entries(state.committee).find(([,v])=>v===String(id)); const leader=state.groups.some(g=>g.leaderId===String(id)); return `<div class="group-bubble ${leader?'is-leader':''} ${committee?'is-committee':''}" draggable="true" data-student-id="${esc(id)}" title="${committee?esc(committee[0]):''}">${committee?'👑 ':''}<span>${label(s)}</span></div>`}
  function render(){const all=current.students.map(s=>String(s.id));const assigned=new Set(state.groups.flatMap(g=>g.studentIds));state.unassignedIds=all.filter(id=>!assigned.has(id));
    modal.querySelector('.group-count').value=state.groups.length;
    modal.querySelector('.unassigned-list').innerHTML=state.unassignedIds.map(id=>bubble(id)).join('')||'<span class="group-muted">已全部分组</span>';
    modal.querySelector('.groups').innerHTML=state.groups.map(g=>`<section class="group-card" data-group-id="${g.id}"><header><strong>${esc(g.name)}</strong><span><input class="group-max" type="number" min="1" value="${g.max}" data-group-max="${g.id}"> 人上限</span></header><div class="group-drop" data-group-id="${g.id}">${g.studentIds.map(id=>bubble(id)).join('')||'<span class="group-muted">拖入学生</span>'}</div></section>`).join('');
    modal.querySelector('.committee').innerHTML=M.ROLES.map(r=>`<label>${r}<select data-role="${r}"><option value="">未设置</option>${current.students.map(s=>`<option value="${esc(s.id)}" ${state.committee[r]===String(s.id)?'selected':''}>${label(s)}</option>`).join('')}</select></label>`).join(''); bindBubbles();
  }
  function moveAt(x,y){const el=document.elementFromPoint(x,y),zone=el&&el.closest('.group-drop');if(!zone||!dragId)return;try{M.add(state,dragId,zone.dataset.groupId);render()}catch(e){toast(e.message)}}
  function bindBubbles(){modal.querySelectorAll('.group-bubble').forEach(el=>{el.addEventListener('dragstart',e=>{dragId=el.dataset.studentId;e.dataTransfer.setData('text/plain',dragId)});el.addEventListener('pointerdown',e=>{dragId=el.dataset.studentId;suppressClick=false;longPress=setTimeout(()=>{const g=state.groups.find(g=>g.studentIds.includes(dragId));if(g){try{M.leader(state,g.id,dragId);render();toast('已设置为组长')}catch(err){toast(err.message)}}suppressClick=true},550)});el.addEventListener('pointermove',e=>{if(longPress){clearTimeout(longPress);longPress=null}if(e.buttons){moveAt(e.clientX,e.clientY)}});el.addEventListener('pointerup',e=>{if(longPress){clearTimeout(longPress);longPress=null}if(!suppressClick)moveAt(e.clientX,e.clientY);dragId=null});el.addEventListener('dragend',()=>{dragId=null})});modal.querySelectorAll('.group-drop').forEach(z=>{z.addEventListener('dragover',e=>e.preventDefault());z.addEventListener('drop',e=>{e.preventDefault();dragId=e.dataTransfer.getData('text/plain');moveAt(e.clientX,e.clientY);dragId=null})});modal.querySelectorAll('[data-group-max]').forEach(i=>i.onchange=()=>{try{M.max(state,i.dataset.groupMax,i.value);render()}catch(e){toast(e.message);render()}});modal.querySelectorAll('[data-role]').forEach(s=>s.onchange=()=>{try{M.role(state,s.dataset.role,s.value);render()}catch(e){toast(e.message)}})}
  function init(){const btn=document.createElement('button');btn.className='btn';btn.id='groupingEntry';btn.textContent='分组与班委';const ref=document.querySelector('#rosterManageBtn');if(ref)ref.parentNode.insertBefore(btn,ref.nextSibling);btn.onclick=open;modal=document.createElement('div');modal.id='groupingModal';modal.innerHTML=`<div class="grouping-panel"><button class="grouping-close">×</button><h2>分组与班委</h2><p class="group-help">拖拽学生气泡到组内；长按气泡设置组长。这里只影响分组页，不影响首页加分。</p><div class="group-toolbar"><label>分组数 <input class="group-count" type="number" min="1" max="30"></label><button class="btn" data-generate>生成/重置分组</button><button class="btn primary" data-save>保存到云端</button></div><div class="group-layout"><div><h3>待分组学生</h3><div class="unassigned-list"></div><h3>班委设置</h3><div class="committee"></div></div><div class="groups"></div></div></div>`;document.body.appendChild(modal);modal.querySelector('.grouping-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};modal.querySelector('[data-save]').onclick=save;modal.querySelector('[data-generate]').onclick=()=>{const n=Number(modal.querySelector('.group-count').value)||1;const old=state;state=M.create(current.students,n,4);old.groups.flatMap(g=>g.studentIds).forEach(id=>{if(state.unassignedIds.includes(id)){const target=state.groups.find(g=>g.studentIds.length<g.max);if(target)M.add(state,id,target.id)}});render();toast('已生成分组，请确认后保存')};}
  document.addEventListener('DOMContentLoaded',init);
})();
