(function(){
const M=window.GroupingModel;let modal,data,state,selected;
const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const st=id=>data.students.find(s=>String(s.id)===String(id));
const bubble=id=>{const s=st(id);if(!s)return '';const leader=state.groups.some(g=>g.leaderId===String(id));const role=Object.values(state.committee).includes(String(id));return `<button class="group-bubble ${leader?'is-leader':''} ${role?'is-committee':''}" data-student="${esc(id)}">${leader||role?'👑 ':''}${esc(String(s.studentNo).slice(-2))} ${esc(Array.from(s.name||'?').slice(-1).join(''))}</button>`};
function render(){modal.querySelector('.group-count').value=state.groups.length;modal.querySelector('.unassigned-list').innerHTML=state.unassignedIds.map(bubble).join('')||'已全部分组';modal.querySelector('.groups').innerHTML=state.groups.map(g=>`<section class="group-card"><header><b>${esc(g.name)}</b><label>上限<input data-max="${g.id}" type="number" min="1" value="${g.max}"></label><span>${g.studentIds.length}/${g.max}</span></header><div class="group-drop" data-target="${g.id}">${g.studentIds.map(bubble).join('')||'拖入或点选学生'}</div><button data-clear="${g.id}">取消组长</button></section>`).join('');modal.querySelector('.committee').innerHTML=M.ROLES.map(r=>`<label>${r}<select data-role="${r}"><option value="">未设置</option>${data.students.map(s=>`<option value="${s.id}" ${state.committee[r]===String(s.id)?'selected':''}>${esc(s.studentNo)} ${esc(s.name)}</option>`).join('')}</select></label>`).join('')}
function put(gid){if(!selected)return;try{if(gid==='unassigned')M.remove(state,selected);else M.add(state,selected,gid);selected=null;render()}catch(e){modal.querySelector('.group-message').textContent=e.message}}
async function save(){const b=modal.querySelector('[data-save]');b.disabled=true;try{const old=JSON.parse(JSON.stringify(data)),next=JSON.parse(JSON.stringify(data));next.grouping=state;await window.saveScheduleCloud(next,old);window.classroomCloudBridge.setData(next);data=next;modal.querySelector('.group-message').textContent='保存成功，云端已同步'}catch(e){modal.querySelector('.group-message').textContent='保存失败：'+e.message+'（原数据未覆盖）'}finally{b.disabled=false}}
function open(){data=JSON.parse(JSON.stringify(window.classroomCloudBridge.getData()));state=M.normalize(data.grouping,data.students);render();modal.classList.add('open')}
function init(){const b=document.createElement('button');b.className='btn';b.id='groupingEntry';b.textContent='分组与班委';document.querySelector('#rosterManageBtn').after(b);b.onclick=open;modal=document.createElement('div');modal.id='groupingModal';modal.innerHTML='<section class="grouping-panel"><button class="grouping-close">×</button><h2>分组与班委</h2><p>默认每组最多4人；点选学生后点击组，长按组内学生设为组长。只影响本页。</p><div class="group-toolbar"><label>分组数<input class="group-count" type="number" min="1" max="30"></label><button data-resize>调整组数</button><button data-save>保存到云端</button></div><p class="group-message"></p><div class="group-layout"><aside><h3>待分组学生</h3><div class="unassigned-list" data-target="unassigned"></div><h3>班委设置</h3><div class="committee"></div></aside><div class="groups"></div></div></section>';document.body.append(modal);modal.querySelector('.grouping-close').onclick=()=>modal.classList.remove('open');modal.querySelector('[data-save]').onclick=save;modal.addEventListener('click',e=>{const s=e.target.closest('[data-student]');if(s){selected=s.dataset.student;return}const t=e.target.closest('[data-target]');if(t)put(t.dataset.target);const c=e.target.closest('[data-clear]');if(c){state.groups.find(g=>g.id===c.dataset.clear).leaderId=null;render()}});modal.addEventListener('change',e=>{try{if(e.target.dataset.max)M.max(state,e.target.dataset.max,e.target.value);if(e.target.dataset.role)M.role(state,e.target.dataset.role,e.target.value);render()}catch(x){modal.querySelector('.group-message').textContent=x.message;render()}});modal.querySelector('[data-resize]').onclick=()=>{const n=Math.max(1,Math.min(30,Number(modal.querySelector('.group-count').value)||1));while(state.groups.length<n){const i=state.groups.length+1;state.groups.push({id:'group-'+i,name:'第'+i+'组',max:4,studentIds:[],leaderId:null})}while(state.groups.length>n){const g=state.groups.pop();state.unassignedIds.push(...g.studentIds)}state.groupCount=n;render()}}
document.addEventListener('DOMContentLoaded',init);
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
  if(!modal)return; const mark=()=>modal.querySelectorAll('[data-student]').forEach(b=>b.draggable=true); mark(); new MutationObserver(mark).observe(modal,{childList:true,subtree:true}); let drag=null;
  modal.addEventListener('dragstart',e=>{const b=e.target.closest('[data-student]');if(!b)return;drag={id:b.dataset.student};e.dataTransfer.setData('text/plain',drag.id);e.dataTransfer.effectAllowed='move'});
  modal.addEventListener('dragover',e=>{if(e.target.closest('[data-target]'))e.preventDefault()});
  modal.addEventListener('drop',e=>{const zone=e.target.closest('[data-target]');if(!zone)return;e.preventDefault();const id=(drag&&drag.id)||e.dataTransfer.getData('text/plain');if(id){selected=id;put(zone.dataset.target)}drag=null});
  modal.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-student]');if(!b)return;drag={id:b.dataset.student,x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture?.(e.pointerId)});
  modal.addEventListener('pointermove',e=>{if(!drag||!drag.x)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8)drag.moved=true});
  modal.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(!d.moved)return;const zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-target]');if(zone){selected=d.id;put(zone.dataset.target)}});
},0));
})();
